from __future__ import annotations

import argparse

from pt.apply.cli import cmd_apply
from pt.context.cli import cmd_context
from pt.tree.cli import cmd_tree


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="pt",
        description=(
            "prompt-tools (pt)\n\n"
            "A small CLI for working with prompt-tools artifacts.\n"
            "Currently available commands:\n"
            "  - pt context  Create a YAML context artifact of a directory\n"
            "  - pt tree     Create a YAML file tree artifact of a directory\n"
            "  - pt apply    Apply a YAML file set into a directory\n"
        ),
    )
    sub = p.add_subparsers(dest="command", required=True)

    p_context = sub.add_parser(
        "context",
        help="Create a YAML context artifact of a directory.",
        description=(
            "Create a YAML context artifact of a directory.\n\n"
            "The command collects text files from PROJECT_DIR (respecting .gitignore and optional .ppignore)\n"
            "and writes a YAML artifact into ./data/contexts/.\n\n"
            "Output format (YAML):\n"
            "  files:\n"
            "    - path: \"relative/path/to/file.ext\"\n"
            "      content: |-\n"
            "        <file contents, indented>\n\n"
            "Notes:\n"
            "  • The \"path\" field is always relative to PROJECT_DIR.\n"
            "  • The \"content\" field is a YAML block scalar (|-), so the file is stored verbatim.\n"
            "  • Binary files are omitted and replaced with: [binary file omitted]\n"
            "  • If PROJECT_DIR is a git repo, file discovery uses git ls-files.\n"
            "    Otherwise it falls back to ripgrep (rg --files).\n"
            "  • If a .ppignore file exists in PROJECT_DIR, its patterns are used to exclude files.\n"
        ),
        formatter_class=argparse.RawTextHelpFormatter,
    )
    p_context.add_argument(
        "project_dir",
        metavar="PROJECT_DIR",
        help="Directory to context (paths inside the YAML are relative to this directory).",
    )
    p_context.set_defaults(func=cmd_context)

    p_tree = sub.add_parser(
        "tree",
        help="Create a YAML file tree artifact of a directory.",
        description=(
            "Create a YAML file tree artifact of a directory.\n\n"
            "This command selects the same files that `pt context` would consider\n"
            "(respecting .gitignore and optional .ppignore), but does NOT embed file contents.\n"
            "Instead, it writes a YAML artifact containing:\n"
            "  • an ASCII tree (tree: |-) with optional line counts per file\n\n"
            "Output is written into:\n"
            "  ./data/trees/<project-name>/<project>_YYYYMMDD_HHMM.yaml\n"
        ),
        formatter_class=argparse.RawTextHelpFormatter,
    )
    p_tree.add_argument(
        "project_dir",
        metavar="PROJECT_DIR",
        help="Directory to analyze (paths inside the YAML are relative to this directory).",
    )
    p_tree.set_defaults(func=cmd_tree)

    p_apply = sub.add_parser(
        "apply",
        help="Apply a YAML file set into a directory.",
        description=(
            "Apply a YAML file set into PROJECT_DIR.\n\n"
            "The command reads YAML in format:\n"
            "  files:\n"
            "    - path: \"relative/path\"\n"
            "      content: |-\n"
            "        ...\n\n"
            "This YAML can be produced by `pt context` or generated by an LLM as a change plan.\n\n"
            "Safety:\n"
            "  • Absolute paths are rejected.\n"
            "  • Path traversal ('..') is rejected.\n"
            "  • Placeholder contents ([binary file omitted], [unreadable file omitted]) are skipped by default.\n"
        ),
        formatter_class=argparse.RawTextHelpFormatter,
    )
    p_apply.add_argument(
        "project_dir",
        metavar="PROJECT_DIR",
        help="Target directory to write files into.",
    )
    p_apply.add_argument(
        "yaml_file",
        metavar="YAML_FILE",
        nargs="?",
        default="files.yaml",
        help="YAML file to apply (default: files.yaml).",
    )
    p_apply.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be written, without writing files.",
        )
    p_apply.add_argument(
        "--no-clobber",
        action="store_true",
        help="Do not overwrite existing files.",
    )
    p_apply.add_argument(
        "--write-placeholders",
        action="store_true",
        help="Write placeholder markers for omitted binary/unreadable files.",
    )
    p_apply.set_defaults(func=cmd_apply)

    return p


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
